apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002 # Puerto TCP del microservicio
  type: ClusterIP