apiVersion: v1
kind: Service
metadata:
  name: tasks-ia-koderx-server-service
spec:
  selector:
    app: tasks-ia-koderx-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP